#!/usr/bin/env bash

######################################################################
## (C)Copyright 2024 Hewlett Packard Enterprise Development LP
######################################################################


SpireServerImage="ghcr.io/spiffe/spire-server:1.8.4"
SpireAgentImage="ghcr.io/spiffe/spire-agent:1.8.4"

# Pull the spire-server docker image if not already exists
if [ -z "$(docker images -q ${SpireServerImage} 2> /dev/null)" ]; then
  echo "=================================================================="
  echo "Pulling spire-server docker image from git hub container registry"
  echo "=================================================================="
  docker pull ${SpireServerImage}
fi
# Exit if image does not exist by now
if [ -z "$(docker images -q ${SpireServerImage} 2> /dev/null)" ]; then
  echo "Error: Failed to find the spire server image in the host"
  exit 1;
fi

# Pull the spire-agent docker image if not already exists
if [ -z "$(docker images -q ${SpireAgentImage} 2> /dev/null)" ]; then
  echo "=================================================================="
  echo "Pulling spire-agent docker image from git hub container registry"
  echo "=================================================================="
  docker pull ${SpireAgentImage}
fi

# Exit if image does not exist by now
if [ -z "$(docker images -q ${SpireAgentImage} 2> /dev/null)" ]; then
  echo "Error: Failed to find the spire agent image in the host"
  exit 1;
fi

# Create a workspace to run this example
workingDir=$(pwd)/workspace/spire/cifar10
mkdir -p ${workingDir}
spireCifarDir=$(pwd)/examples/spire/cifar10
spireDir=$(pwd)/examples/spire
org_1_trust_domain="org1.swarm.learning"
org_2_trust_domain="org2.swarm.learning"

# Copy files into the worksapce
cp -r ${spireCifarDir}/swci ${workingDir}/
cp -r ${spireCifarDir}/swop ${workingDir}/
cp -r ${spireCifarDir}/model ${workingDir}/
cp -r ${spireCifarDir}/spire-server ${workingDir}/
cp -r ${spireCifarDir}/spire-agent ${workingDir}/

# Copy run task file to tmp location. To keep the path same between the hosts.
mkdir -p /tmp/spire/cifar10/model
cp ${spireCifarDir}/model/cifar10.py /tmp/spire/cifar10/model/cifar10.py

# Creates volume sl-cli-lib and moves the whl file in to it.
moveWhlToVolume()
{
    docker volume rm sl-cli-lib
    docker volume create sl-cli-lib
    docker container create --name helper -v sl-cli-lib:/data hello-world
    docker cp lib/swarmlearning-client-py3-none-manylinux_2_24_x86_64.whl helper:/data
    docker rm helper
}
if [[ -f "$(pwd)/lib/swarmlearning-client-py3-none-manylinux_2_24_x86_64.whl" ]]
then
    echo "Wheel file found in the desired location."
else
    echo "Error: It is required to keep the whl file in the lib folder of this base(swarm-learning) directory."
    exit 1; 
fi
removeRunningSpireContainers()
{
    docker rm -f spire-server spire-agent
}
moveWhlToVolume
removeRunningSpireContainers