#!/usr/bin/env bash

######################################################################
## (C)Copyright 2022 Hewlett Packard Enterprise Development LP
######################################################################

HOST_IDX=$1
[[ -z "$1" ]] && { echo "Host Index is empty" ; exit 1; }
echo "Host Index: "${HOST_IDX}

# Create a workspace to run this example
workingDir=$(pwd)/workspace/reverse-proxy/cifar10
mkdir -p ${workingDir}
reverseProxyCifarDir=$(pwd)/examples/reverse-proxy/cifar10

# Copy files into the worksapce
cp -r ${reverseProxyCifarDir}/swci ${reverseProxyCifarDir}/swop ${workingDir}/
cp -r ${reverseProxyCifarDir}/model $(pwd)/examples/utils/gen-cert ${workingDir}/

# Copy run task file to tmp location. To keep the path same between the hosts.
mkdir -p /tmp/reverse-proxy/cifar10/model
cp ${reverseProxyCifarDir}/model/cifar10.py /tmp/reverse-proxy/cifar10/model/cifar10.py
#cp -r ${reverseProxyCifarDir}/model/ /tmp/reverse-proxy/cifar10/

# Generates self-signed certificates on the workspace. 
generateCertificates()
{
    "./workspace/reverse-proxy/cifar10/gen-cert"      \
    -e reverse-proxy/cifar10                          \
    -i ${HOST_IDX}
}

# Creates volume sl-cli-lib and moves the whl file in to it.
moveWhlToVolume
generateCertificates
